### ISSUE TITLE
bootRepackage default value when using 'createLibraryProject'

### ISSUE THREAD

**Issue by Blackbaud-MattWalsh** [blackbaud/gradle-templates#68]
Not sure if this is helpful or not, but I created a new library by using the `createLibraryProject` command. Then I created the necessary files in my project and wanted to test by doing a `publishToMavenLocal`, but I received the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRepackage'.
> Unable to find main class
```

@Blackbaud-DiHuynh pointed out that I should probably add the following to my project's `build.gradle` and everything worked:

```
springBoot {
    bootRepackage {
        enabled = false
    }
}
```

Should this be a default value when creating a new library project?

**Comment by Blackbaud-MikeLueders** [comment]
the `spring-boot` gradle plugin should not be applied to library projects, not sure why it is.  i'll take a look

**Comment by Blackbaud-MikeLueders** [comment]
@MatthewMazaika did you add the `spring-boot` plugin yourself?  i just generated a library project and can publish fine.  closing for now, feel free to re-open with steps to reproduce.
